src/component_pool.hpp
src/registry.hpp

All class templates from the ECS are defined as `final`. In my opinion this is not sensible. In my concrete application I want to be able to forward declare the ECS class without retyping all template parameters (forward declaration of typedefs is not possible). The easiest way to do this would be to inherit from the EnTT types:
```
class EntityComponentSystem : public entt::StandardRegistry<EntityType, ...> {/* stays empty */};
```
now I can forward declare the `EntityComponentSystem` class in other parts of the project.
In general I don't see an advantage of using `final` in this context and I would propose to remove the  specifiers from the headers.

Remove final specifier from all class templates

---

src/entt/entity/sparse_set.hpp

In the error message, an explicit constructor is mentioned; trying to enable the construction explicitly using the name of the type.

fixing clang build

---

src/entt/entity/sparse_set.hpp

src\entt\entity\sparse_set.hpp(617): warning C4458: declaration of 'direct' hides class member
Only triggered by /W4. The rest of the library compiles fine so might as well fix this one :)
Just renaming temporary variable. Wasn't exactly sure of a correct name.

Fix MSVC 2017 warning C4458

---

src/entt/entt.hpp

Or is there a reason why it is not included?

Add Dispatcher header to EnTT global include

---

src/entt/entity/prototype.hpp

I had this implementation lying around for a while so I thought I should clean it up and open a pull request. Issue #56 has a discussion about this feature. Here's an example:
```C++
#include <entt/entity/prototype.hpp>
struct Position {
int x;
int y;
};
struct Sprites {
int id;
int frames;
};
enum class TileType {
WALL,
ENEMY
};
// not every entity can be initialized with EXACTLY the same components
uint32_t make(const entt::DefaultPrototype &proto, entt::DefaultRegistry &reg, Position pos) {
uint32_t entity = proto(reg);
reg.assign<Position>(entity, pos);
return entity;
}
int main() {
// imagine we’re initialising prototypes from files
entt::DefaultPrototype wall;
wall.assign<Sprites>(0, 4);
wall.assign<TileType>(TileType::WALL);
entt::DefaultPrototype enemy;
enemy.assign<Sprites>(4, …
```

Implement entt::Prototype

---

src/entt/entity/registry.hpp

since size_t and unsigned int are different on windows we have to cast to entity_type.

fix warning on windows C4267

---

src/entt/signal/delegate.hpp

What do you think about it? This could be achieved using `delegate == {}` I guess, but maybe the `empty()` member function is more expressive...

exposing empty delegate check

---

src/entt/signal/delegate.hpp

I had compilers errors trying to connect a `void(bool)` function to a delegate; the compiler complained about not being able to return a value of type `void`. This should fix.

allowing void() delegates

---

src/entt/core/family.hpp
src/entt/core/ident.hpp
src/entt/core/monostate.hpp
src/entt/entity/registry.hpp
src/entt/entity/view.hpp
src/entt/locator/locator.hpp
src/entt/process/scheduler.hpp

- Removed list initialization of static members;
- Replaced Identifier::get constexpr function with helper struct internal::IndexOf;
- Added default ctor for Monostate to let it be {}-initialized.
- Replace pivot trick in Registry::connect/disconnect with RemoveTypeFromTuple helper struct.
- Rename begin/end members in View and RealtimeView iterators in order to fix GTest trying to interpret iterators as containers.
- Add casts to Scheduler::then to fix function overload ambiguity.

Port for VS 2015

---

src/entt/meta/meta.hpp

Was not able to call the `resolve<T>()` function under g++ 8.2.0 cause of this missing noexcept.

fixed invalid conversion from lambda to noexcept function ptr

---

CMakeLists.txt

This commit fixes a bug where find_package(EnTT) fails when EnTT is
installed using vcpkg.
The bug occurs because EnTTConfig.cmake.in calls
check_required_components(), yet the call to
configure_package_config_file() in CMakeLists.txt that generates
EnTTConfig.cmake is passed NO_CHECK_REQUIRED_COMPONENTS_MACRO. This
causes CMake to error when it tries to parse the output EnTTConfig.cmake
file if that file is generated from EnTTConfig.cmake.in e.g. when
installing EnTT using vcpkg.

Fix find_package(EnTT) when EnTT is installed using vcpkg

---

src/entt/core/algorithm.hpp

Currently, `insertion_sort::operator()` in core/algorithm.hpp is implemented like this:
template<typename It, typename Compare = std::less<>>
void operator()(It first, It last, Compare compare = Compare{}) const {
auto it = first + 1;
while(it != last) {
auto value = *it;
auto pre = it;
while(pre != first && compare(value, *(pre-1))) {
*pre = *(pre-1);
--pre;
}
*pre = value;
++it;
}
}
Notice that `first` is incremented at the very beginning. This is undefined behaviour if `first` is the past-the-end-iterator. Therefore, the following example crashes with VC++ 14.16:
#include <entt/core/algorithm.hpp>
#include <vector>
int main()
{
std::vector<int> v{};
entt::insertion_sort sort{};
sort(v.begin(), v.end())
}
This can easily be fixed by comparing `first` and `last` at the beginning of the …

UB/Crash in entt::insertion_sort

---

README.md

GCC8 does not auto-deduce the template parameter for entt::registry, so it has to be provided explicitly.

Fix compile error when compiling example with GCC8

---

src/entt/entity/sparse_set.hpp
test/entt/entity/sparse_set.cpp

First off, thank you for creating such an amazing piece of free software! 
I started creating a [similar library](https://github.com/cstegel/glomerate) to this when I surveyed the landscape of open source entity component systems a couple years ago and did not like what I found. I only needed it for one project at the time and then stopped working on it shortly after the project was done. When I searched for open source ECS recently I stumbled across `entt` and I am very impressed!
Any ways, on to the actual bug and fix...
Previously, a component's constructor that throws would cause the sparse
set to think that the entity still exists in the set. This is because the underlying
sparse set that stores the entities will have its entry added before the component 
is added to the component …

Fix sparse_set invalid state when component constructor throws

---

src/entt/entity/registry.hpp

The documentation for a number of functions in registry stated that they take forward iterators but calculated the distance between iterators in a way that required random access iterators.

Fix getting distance between forward iterators

---

conanfile.py

Add a method to the recipe that maps the include path to "src" when the package is put into "editable mode". See:
https://docs.conan.io/en/latest/developing_packages/editable_packages.html

Conan: Support package in editable mode

---

.gitignore
BUILD.bazel
WORKSPACE
bazel/BUILD.bazel
bazel/copts.bzl
test/benchmark/BUILD.bazel
test/entt/core/BUILD.bazel
test/entt/entity/BUILD.bazel
test/entt/locator/BUILD.bazel
test/entt/meta/BUILD.bazel
test/entt/process/BUILD.bazel
test/entt/resource/BUILD.bazel
test/entt/signal/BUILD.bazel
test/lib/BUILD.bazel
test/mod/BUILD.bazel
test/snapshot/BUILD.bazel

closes https://github.com/skypjack/entt/issues/287
Results of `bazel test //...` with gcc 8.30:
Benchmark compiles/runs successfully (after merging https://github.com/skypjack/entt/pull/290) with `bazel run //test/benchmark`

Bazel Support (#287)

---

CMakeLists.txt

This prevents checking of C compiler

Mark CMake project explicitly as C++

---

CMakeLists.txt

Well, MSVC is not the only compiler on Windows, we use also `Clang` that use the same compiler flags as `MSVC` (clang-cl)
According to that, when you detect clang we also should detect platform.

[Fix CMake for Clang users on Windows]

---

appveyor.yml

This brings up improved compilation speed and saner error messages.

Use Ninja on AppVeyor

---

src/entt/entity/observer.hpp
test/entt/entity/observer.cpp

Hello! I think `entt::collector` has a bug. The `where` function actually changes the first added matcher, not the last one. In the following example both of `where` calls update the `group` matcher instead of preceding `replace` matcher.
```
entt::observer(registry, entt::collector.group<ComponentA, ComponentB>()
.replace<ComponentA>().where<ComponentA, ComponentB>()
.replace<ComponentB>().where<ComponentA, ComponentB>())
```
Here's the fix.

Fix entt::collector.where

---

CMakeLists.txt

- Adds an alias to the library for in-source builds. IE: `add_subdirectory`
- Adds a namespace to the exported library so it also works with `find_package` and any other scenario where you don't build in-source
Tested on real world project wacman to both changes above and it built as expected.

Add namespace qualifier in CMake (close #321)

---

test/entt/meta/meta.cpp

Four tests are added:
* 2 tests for testing the good case: only one property is registered with
either `prop` or `props` function call;
* 2 tests for testing the bad cas: multiple properties are registered with
either `prop` or `props` function call.
Signed-off-by: Innokentiy Alaytsev <alaitsev@gmail.com>

[353] Tests for detecting the bug

---

docs/md/faq.md
src/entt/core/hashed_string.hpp
src/entt/core/type_traits.hpp

The new macro can be used in user code for suppressing warnings when using
entt::hashed_string in constexpr context. The workaround provided in the FAQ
```c++
#define HS(str)\
__pragma(warning(push))\
__pragma(warning(disable:4307))\
entt::hashed_string{str}\
__pragma(warning(pop))
#define HS(str) entt::hashed_string{str}
```
can be reduced to
```c++
#define HS(str) ENTT_HASHED_STRING_SUPPRESS_WARNING entt::hashed_string{str}
```
The new macro is also applied in the `ENTT_NAMED_TYPE` macro to reduce the
number of false warnings in user code. It is suggested that users should use
the macro also in their own specialisation of the `entt::named_type_traits`
template class.
The documentation was updated to mention a simplified form of warning
suppression and the newly added macro.
closes #348

Intoduced a macro for suppressing MSVC warning C4307

---

AUTHORS
cmake/in/cereal.in
cmake/in/duktape.in
cmake/in/googletest.in

very useful in CI/CD pipelines
Signed-off-by: Stefano Fiorentino <stefano.fiore84@gmail.com>

adding git_shallow to cmake deps helps reducing building time

---

BUILD.bazel
README.md
WORKSPACE

Hey it's me again the bazel guy.
I was updating my project to the latest version of EnTT (v3.3.0) and noticed it no longer worked with bazel! I see it was removed due to it not being maintained. I'll admit I hadn't been running the tests so I didn't notice that shortly after it was initially added the tests no longer worked with bazel. However my project had been running EnTT v3.2.2 just fine because the user facing target `@com_github_skypjack_entt//:entt` had been working.
So that brings us to this PR. This PR includes only the user facing target and no tests to make it simpler.

Re-added bazel support

---

docs/md/entity.md

example should match how legacy EnTT worked, raw isn't available for empty types.

Update clone example to handle empty types

---

docs/md/entity.md

Hello.
I've fixed a small typo in docs (need to check if entity has `velocity` component, not `comp` component).

Fix small typo in docs

---

README.md

The `entt` packages for `build2` are available there: https://cppget.org/entt
At the moment only `v3.3.0` is avaialble as a "stable" package, `v3.3.1` to `v3.4.0` are currently being tested (see https://queue.cppget.org/entt/ ) and will be available soon.
The sources for the `build2` package are there: https://github.com/build2-packaging/entt
For the moment I didn't made the `build2` package build the tests (only a very minimal test to check that users can use the package, ussing the example code from the readme). I will add `entt`'s original tests later as it is not required for consuming the library.
There is also no build option sets for now, only the default.
Please tell me if this is too much information in the Readme, I can remove some details.

Added `build2` package info

---

AUTHORS
src/entt/entity/snapshot.hpp
test/entt/entity/snapshot.cpp

Replaced calls to std::as_const with std::move so that components can
be moved into place instead of copied when reading them in from a
snapshot.

snapshot: components no longer need to be copyable

---

AUTHORS
src/entt/entity/view.hpp

Closes #530
Closes #96 
This fixes the `std::min` and `std::max` functions being parsed as macros when `<windows.h>` is included and `#define NOMINMAX` is neither present nor included before all other headers.
Note: There is a use of `std::max` in the single-include header that does not appear anywhere else in the separated-out code. I could not find where the single-include header is generated to see where it's coming from.

Fix C4003 NOMINMAX bug

---

src/entt/meta/meta.hpp
test/entt/meta/meta_any.cpp
test/entt/meta/meta_type.cpp

Implemented shortcuts for invoking meta-functions and getting and setting meta-data directly from `meta_type` and `meta_any` instances.
I'll sign commits a bit later - don't have my key with me now.
Once PR is reviewed, I'll squash things.
I suggest cherry-picking the trailing spaces fixing commit even without PR.

Data and func shortcuts

---

docs/md/entity.md
src/entt/entity/handle.hpp
test/entt/entity/handle.cpp

Following the brief discussion on Discord after my initial impressions of `entt::handle` that were introduced in #513 I'm creating a pull request with proposed changes.
This is a draft and the code will probably change after discussions or will be rejected, so I only changed tests to compile with the current code but didn't add new ones yet or fix the failures. I didn't update the documentation too.
It's not possible to store a default initialized and truly invalid handle that doesn't point to any registry and entity.
In my case there are a lot of types that live outside the ECS and point to certain entities in order to inspect them or operate on them. Not pointing to any entity is also a valid case though. Current `entt::handle` makes the described approach much less elegant since it has …

Truly invalid entt::handle

---

test/CMakeLists.txt

Besides MSVC (and compatible compilers like clang-cl) there's also GCC (MinGW) and GNU-like Clang on Windows. Therefore setting command line flags in CMake should check for `MSVC` instead of `$<PLATFORM_ID:Windows>`.

Allow compilation for Windows with GNU-like compilers

---

docs/md/entity.md

I think this is only a typo, order of reference for const and non const types were swapped around in the intro of "Types: const, non-const and all in between" section.

Fixed const, non-const types section intro in entity.md

---

src/entt/meta/meta.hpp

This change lets the user detect whether an `entt::meta_any` contains a `nullptr` of any type (once it has been dereferenced).
```
int* v = nullptr;
entt::meta_any any = v;
if (!*any) {
std::cout << "nullptr!" << std::endl;
}
```

Allow checking meta_any for nullptr

---

.github/workflows/build.yml
.github/workflows/coverage.yml
CMakeLists.txt
README.md
test/CMakeLists.txt

Fixes #584 
Cache variables as well as normal variable names have been prefixed with ENTT. Relevant changes have been made to the README and workflow files.

Prefix CMake Variables with ENTT.

---

docs/md/core.md

The given example doesn't compile without the "L" prefix to the string.

Fixed missing prefix "L"

---

src/entt/core/any.hpp

PS4 headers doesn't define `__cpp_lib_launder` which fails to compile with `-Werror`
Thanks for the nice library

PS4 build fix

---

CMakeLists.txt
cmake/in/entt.pc.in

Closes #673.
This will generate a new file called `entt.pc`, which can be used by pkg-config to provide compiler flags for EnTT.
Installing EnTT like this:
```
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~/entt-install
$ make
$ make install
```
will provide the file in `~/entt-install/lib64/pkgconfig/entt.pc`.
If this file can be found in a folder from `PKG_CONFIG_PATH`, then `pkg-config --cflags entt` will provide the include flag for the compiler.
```
$ PKG_CONFIG_PATH=~/entt-install/lib64/pkgconfig pkg-config --cflags entt
-I/home/seamas/entt-install/include
```
This will make it easy for distro maintainers to install the library so build systems (like Meson, for example) can find that EnTT is installed on the system and include it automatically in projects.
Side …

build system: add pkg-config support

---

src/entt/entity/snapshot.hpp

In MSVC the `std::array::operator[]` is `[[nodiscard]]` and the return value is discarded in `snapshot.hpp`
I only got this warning when using MSVC.
Compilers tested:
```
MSVC 19.29.30038.1
gcc-9.3
```

fix warning for discarding a nodiscard

---

src/entt/meta/factory.hpp
src/entt/meta/node.hpp

These changes reduce, under some quite common circumstances (like `id_type` and `meta_traits` being 4 bytes under an x64 system), the size of `meta_data_node`, `meta_func_node` and `meta_type_node` by 4 bytes each.

meta: reduced size of 3 node structures

---

AUTHORS
TODO
src/entt/entity/registry.hpp

This is a draft PR, since it contains changes that I think would be good to merge, but also other changes that are more explorative at this stage. I have been trying to understand the behavior of EnTT when it comes to reaching the limits of the registry: too many entities, or too many cycles of create/release (overflow of version).
1. I think I have found an issue in `basic_registry::generate_identifier`, which can return values that cannot be represented in the entity mask, resulting in very odd behavior. I fixed this and added a test.
2. Trying to understand the logic of version overflow, I added a more extensive test that checks overflow for all entity values. I was surprised by the behavior. First, the registry will prefer to overflow even if there are free entity slots available; I …

Overflow of version and max number of entities

---

test/example/entity_copy.cpp

This adds a TODO comment above some test code statements that workaround #827. Without this context, why those lines are necessary is a little confusing.

test: add mention of storage initialization workaround (ref #827)

---

src/entt/entity/storage.hpp

storage_iterator (storage.hpp) is (or at least might be) templatized using a container (e.g. std::vector) of pointers to components, for example when inserting components into storage via insert().
Therefore, when accessing component_traits, the pointer must be removed (std::remove_pointer_t).

Fixed storage component_traits

---

README.md

I'm the author of [vcpkg.link](https://vcpkg.link) and currently trying to improve the discoverability of Vcpkg ports since it helps other developers to integrate libraries into their projects.
This PR aims to add a fresh new [shields.io](https://shields.io) badge (https://github.com/badges/shields/pull/8923) that provides at a glance in the README which version of EnTT is available on [Vcpkg](https://vcpkg.link/ports/entt).

Add Vcpkg badge

---

src/entt/container/dense_map.hpp
src/entt/container/dense_set.hpp

There is ambiguity between std::max() and MAX macro, which propagates via "Windows.h", on the Windows platform. In order not to bother the user with the NOMINMAX definitions, the bracketing method was chosen.

dense_*: workaround for the max() ambiguity with MAX macro.

---

src/entt/core/type_info.hpp
src/entt/entity/entity.hpp

Using the experimental C++20 modules support in recent builds of Clang, EnTT currently causes compilation errors when included as part of the global module fragment in a module interface unit that exports part of EnTT's API and is then imported and used by a different translation unit. Here is a minimal example (note the "error: no matching function for call to 'popcount'" in the output): https://godbolt.org/z/9vTjz9Prh
The reason seems to be that certain function declarations that are implicitly required by the implementation aren't exported into the module interface since they are erroneously marked 'static' and have internal linkage when they should (presumably) be 'inline'. I found that changing these declarations accordingly fixed the problem and made EnTT work well with C++20 …

Fix C++20 global module fragment inclusion

---

docs/md/entity.md

Using `const auto &...`  for the arguments doesn't work because the `entt::entity` overload has priority over the component (in this case, `renderable`) overload.
https://github.com/skypjack/entt/issues/535#issuecomment-667853342

Docs - Fix typo in Sorting section

---

docs/CMakeLists.txt

Building only the documentation without enabling testing (i.e. without setting `ENTT_BUILD_TESTING=ON`) failed. The bug occurred because `FetchContent` wasn't included in `docs/CMakeLists.txt`. However it was included in `test/CMakeLists.txt`, which explains why the bug wasn't triggered when testing was enabled.
Note that this bug is also present in the latest release (v3.12.2).

Fixes documentation generation bug

---

docs/md/entity.md

Pointing it to wip, but maybe you want this in master ?

cleanup grammar nitpicks in the context section

---

src/entt/config/config.h

Closes #1163 
Before:
```
Assertion failed: (contains(entt)), function index, file sparse_set.hpp, line 717.
/bin/sh: line 1: 96048 Abort trap: 6
```
After:
```
Assertion failed: (contains(entt) && "Set does not contain entity"), function index, file sparse_set.hpp, line 717.
/bin/sh: line 1: 96499 Abort trap: 6
```

Print assertion message upon failure

---

src/entt/entity/mixin.hpp
test/entt/entity/storage_signals.cpp

This is the promised implementation for #1165, adding support for binding static functions of components to signals related to their lifetime. 
The functions should be named `on_construct`, `on_update` and `on_destroy`, be `static` to the component and have their signature as `void (entt::basic_registry<Entity, Alloc> &reg, Entity id)` to be considered by the default storage. The functions will be registered only for the specified registry specializations and only if the pool/storage of your component is the default storage. 
A component can implement any of these functions and doesn't need to implement all of them for the feature to work. Also note that these functions will also be available to the named pools of the component as well. If you don't want this behavior, you should have two …

Automatic signal registration for components

---

src/entt/core/hashed_string.hpp

Spaces here are deprecated, and fire the warning -Wdeprecated-literal-operator

Remove extra spaces

---

src/entt/meta/meta.hpp
src/entt/meta/node.hpp

We don't need a complete `meta_type` for the target type of the `try_cast`, but we are OK with the `type_info`.

Avoid pointless lookups in try_cast

---

src/entt/entity/sparse_set.hpp
src/entt/entity/view.hpp
src/entt/meta/factory.hpp
test/entt/entity/view.cpp

Views are pretty much a core utility of EnTT already and there is good support for many common operations. One of them is joining with other views, especially useful when one view might have named pools. However, the syntax becomes a little noisy when you need to join a view with one storage, which most often is a named `void` storage or a storage out of the registry (from my experience). To do this, we currently have to do something like:
```cpp
entt::storage_for_t<void> dirty_entities;
// ...
auto view = registry.view<C1, const C2>() | entt::basic_view{dirty_entities};
for (auto id : view) {
// ...
}
```
To address this, I propose to add a `join` function to `basic_view`, which works similarly to the existing `operator|`, except that it only accepts a storage as a parameter instead of a …

Joining views with storages

---

src/entt/config/macro.h
src/entt/core/hashed_string.hpp

It's easy to introduce unnecessary runtime-overhead by accident. The documentation even states this:
> No string-to-number conversion will take place at runtime **if used carefully**.
Applying ``consteval`` on the two members, which accept an c-array, seems appropriate as they are obviously intended for compile-time construction.
Making the literals ``entt::literal::_hs`` and ``_hws`` ``consteval`` too, because there is literally no reason to use them at runtime.

Apply ``consteval`` on appropriate ``basic_hashed_string`` related functions 

---

src/entt/container/dense_map.hpp
test/entt/container/dense_map.cpp

C++26 has this, so why not add it. Does not need any language/library feature.

Transparent lookup for `dense_map::at`
