skypjack/entt

README.md, src/entt/entity/registry.hpp, test/entt/entity/registry.cpp
Overall improvement of the registry. See #40 for more details.
=> Fewer allocations, faster destroy

src/entt/process/scheduler.hpp
see https://github.com/skypjack/entt/issues/145
=> update the then methods to fix issue I was getting with g++-8 compiler

src/entt/entity/snapshot.hpp, test/snapshot/snapshot.cpp
I ran into this when trying deserialize null entity member relationships.
=> allow for null entity members

docs/entity.md
=> [DOCS] removed excess "registry." in groups code sample

src/entt/entity/registry.hpp
fixing some shadow warnings I was getting with godot compiling entt
you can remove the stackoverflow link but sometimes I like to link explanations of things I consider c++ magic.
=> fix shadow warnigns and positive lambda explanation

test/benchmark/benchmark.cpp
only one entity has all the components
=> benchmark fix

scripts/amalgamate.py, scripts/config.json, single_include/entt/entt.hpp
Usefull for using in godbolt example:
https://godbolt.org/z/lqlKGS
=> add single include of EnTT framework

src/entt/resource/handle.hpp, test/entt/resource/resource.cpp
Added mutable (non-const) variants of the resource handle accessors.
=> mutable overloads for resource accessors

src/entt/core/hashed_string.hpp, src/entt/entity/actor.hpp, src/entt/entity/group.hpp, src/entt/entity/helper.hpp, src/entt/entity/prototype.hpp, src/entt/entity/registry.hpp, src/entt/entity/runtime_view.hpp, src/entt/entity/sparse_set.hpp, src/entt/entity/storage.hpp, src/entt/entity/view.hpp, src/entt/locator/locator.hpp, src/entt/meta/factory.hpp, src/entt/meta/meta.hpp, src/entt/resource/handle.hpp, src/entt/signal/dispatcher.hpp, src/entt/signal/emitter.hpp
Reading more of the source I stumbled over a few more uses of `inline` that aren't needed.
=> Remove superfluous inlines.

src/entt/resource/cache.hpp, test/entt/resource/resource.cpp
Thanks to @Kerndog73 for the implementation details!
Also add it to the wiki article on *Crash Course: resource management*.
=> each() function for resource_cache

AUTHORS, test/benchmark/benchmark.cpp
I ran into this while working on https://github.com/skypjack/entt/issues/287
=> benchmark to use entt::component

docs/md/links.md
I added the link to a tower defense I made using your library. Thanks for your work !
=> [doc] Add link to Mirror lasers & Robots project

src/entt/meta/factory.hpp, test/entt/meta/meta.cpp
Implemented a function for adding a list of properties to meta-item.
=> Properties list

docs/md/entity.md
fix stamp example to be valid code
=> Update stamp example

docs/md/entity.md
=> Small typo fix in wiki

src/entt/entity/registry.hpp
This pull request is in response to discussions in issue skypjack/entt#215.
=> Add a note to registry::try_get documentation

CMakeLists.txt, docs/md/entity.md, docs/md/meta.md, docs/md/poly.md, src/entt/core/hashed_string.hpp, src/entt/entity/entity.hpp, src/entt/entity/organizer.hpp, src/entt/meta/factory.hpp, test/entt/container/dense_map.cpp, test/entt/container/dense_set.cpp
This revision includes:
- Correct minor typos
=> Correct minor typos

src/entt/signal/dispatcher.hpp, test/entt/signal/dispatcher.cpp
This enabled calling size() and size<Event>() to dispatcher to check how many pending events there is to be processed on next update.
=> enables fetching the number of pending events (size) of dispatcher

AUTHORS, src/entt/signal/dispatcher.hpp, test/entt/signal/dispatcher.cpp
=> dispatcher: enable fetching the number of pending events

src/entt/core/tuple.hpp, test/entt/core/tuple.cpp
As we already discussed on discord, I would like to see such a helper type in your library. It really makes working with ranges or legacy algorithms more enjoyable.
=> WIP: apply_fn functional type

docs/md/entity.md
Feeling encouraged in https://github.com/skypjack/entt/discussions/832#discussioncomment-3372370, I've added to the [entity.md](https://github.com/skypjack/entt/blob/master/docs/md/entity.md) sections that cover:
* Iterating multi type views in a specified order
* Reverse-iterating views
=> Add to crash course sections about sorting and reverse-iterating views

src/entt/config/version.h
Adds a the "Arch" ECS to the references.MD file :)
=> Add "Arch" ECS to the references.md

src/entt/entity/organizer.hpp, test/entt/entity/organizer.cpp
=> Fix organizer::vertex::prepare not creating component pools

README.md
I noticed that there's a vcpkg badge already, and that this is also available on conan center.
=> Add conan badge to README

test/CMakeLists.txt
=> fix delegate compare test in Release mode
